### PR TITLE
Upload data for experiments

### PR DESCRIPTION
**Pull request by fabianp**

### CODE REVIEW

**Comment by fabianp** [comment]
solves #3

**Comment by fabianp** [comment]
ping @elena-kalinina

**Comment by elena-kalinina** [comment]
Hi Fabian sorry I am on holiday this week week and I don't have my pic with
me so I cannot test your new code :( I am back next Tuesday if will be
looking for into that immediately thanks for fixing the problem!!
 Best Elena

Il lun 11 feb 2019, 16:39 Fabian Pedregosa <notifications@github.com> ha
scritto:

**Comment by fabianp** [comment]
@elena-kalinina : please merge, there's no need to review, its just that I don't have permissions to push code to your repo

**Comment by elena-kalinina** [comment]
OK I will sorry for the delay

Il gio 28 feb 2019, 15:30 Fabian Pedregosa <notifications@github.com> ha
scritto:

**Pull request merged**
